config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: [:new, :create]
  resources :contacts
  resources :csv_files

  get 'home/index'
  root 'csv_files#index'
end

app/views/layouts/_alerts.html.slim
- if flash[:notice]
  = display_alert class: 'alert-success'
    = flash[:notice].html_safe
    = flash[:alert].html_safe if flash[:alert]
    = flash[:error].html_safe if flash[:error]
- elsif flash[:alert]
  = display_alert class: 'alert-warning'
    = flash[:alert].html_safe
    = flash[:error].html_safe if flash[:error]
- elsif flash[:error]
  = display_alert class: 'alert-danger'
    = flash[:error].html_safe

app/views/layouts/_navbar.html.slim
- if user_signed_in?
  nav.navbar
    ul.nav
      li.nav-item.dropdown.hidden-xs
        = link_to '#', class: 'nav-link navbar-avatar', data: { toggle: 'dropdown' }
          span
            = current_user
            = icon 'fas', 'chevron-down', class: 'pl-2'
        .dropdown-menu.dropdown-menu-right
          = link_to edit_user_registration_path, class: 'dropdown-item'
            = icon 'fas', 'user-cog'
            = t '.edit_user'
          span.navbar-divider
          = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item'
            = icon 'fas', 'sign-out-alt'
            = t '.sign_out'

app/views/layouts/_sidebar.html.slim
- if user_signed_in?
  aside
    nav.navbar
      = link_to root_path, class: 'navbar-brand'
        = image_tag 'brand-logo.svg', class: 'brand-logo'
    = content_tag :ul, class: "nav active", id: 'sidebar_content'
      = content_tag :li, class: 'nav-item nav-avatar'
        .nav-link
          = link_to edit_user_registration_path, class: 'user-display'
            = current_user


      = sidebar_link_to csv_files_path, text: CsvFile.pluralize, icon: 'file-upload'
      = sidebar_link_to contacts_path, text: Contact.pluralize, icon: 'address-book'
      = sidebar_link_to users_path, text: User.pluralize, icon: 'user'

app/views/layouts/application.html.slim
doctype html
html
  head
    title = yield :title
    = content_tag :meta, nil, name: 'viewport', content: 'width=device-width, initial-scale=1'
    = content_tag :meta, nil, name: 'turbolinks-cache-control', content: 'no-cache'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    == render 'layouts/sidebar'
    main
      == render 'layouts/navbar'
      .container-fluid
        == render 'layouts/alerts'
        = yield